# https://taskfile.dev

version: '3'

tasks:

  test:
    desc: Run tests
    dir: server
    cmds:
      - task: reset-db
      - cargo nextest run --workspace

  migrate:
    desc: Run database migrations
    dir: server
    cmds:
      - cargo sqlx migrate run

  drop-db:
    desc: Drop all tables (reset public schema)
    cmds:
      - docker-compose exec -T postgres psql -U local -d local -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

  reset-db:
    desc: Reset the database and run migrations
    cmds:
      - task: drop-db
      - task: migrate

  psql:
    desc: Connect to the PostgreSQL container via bash
    cmds:
      - docker-compose exec postgres bash

  dev:
    desc: Start the development server
    dir: server
    cmds:
      - cargo run --bin main

  docker-rebuild:
    desc: Full Docker rebuild
    cmds:
      - docker-compose down --volumes --remove-orphans
      - docker image prune -af
      - docker volume prune -f
      - docker-compose build --no-cache
      - docker-compose up -d
      - task: migrate
