[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
anyhow.workspace = true
uuid.workspace = true
chrono.workspace = true
mockall.workspace = true
