[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
anyhow.workspace = true
tokio.workspace = true
validator.workspace = true
serde_json.workspace = true
uuid.workspace = true
domain = { path = "../domain" }

[dev-dependencies]
